### ISSUE TITLE
[change] API: use mixins from openwisp-users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#142]
We should change the code of this module to use the new API classes and mixins added to openwisp-users, which were based on the code from this module so should be backward compatible, however, I found out a few issues:

- some classes in openwisp-users were not taking into account the `organization_lookup` field, hence queries were failing to find the right organization field, I solved this in https://github.com/openwisp/openwisp-users/tree/improve-api-mixins, but tests are missing, we need at least one test in openwisp-users. Issue: https://github.com/openwisp/openwisp-users/issues/255.
- a lot of `assertNumQueries` tests are failing! It looks like the number of queries increased between 2 and 3 queries for each endpoint, we should understand what the additional queries are doing, if they're really needed or not, if the extra queries are generated by mistake or not and what we can do to fix it. Issue: https://github.com/openwisp/openwisp-users/issues/256

I started this work on this branch: https://github.com/openwisp/openwisp-firmware-upgrader/tree/openwisp-users-api-mixins, it needs this other branch from openwisp-users to work: https://github.com/openwisp/openwisp-users/tree/improve-api-mixins, I had to give up because it's taking longer than expected and I hope @ManishShah120 you can help me to finish this. 

PS: I think we should also change the definitions of the API views to use tuples instead of lists.

**Comment by ManishShah120** [comment]
> a lot of assertNumQueries tests are failing! It looks like the number of queries increased between 2 and 3 queries for each endpoint, we should understand what the additional queries are doing, if they're really needed or not, if the extra queries are generated by mistake or not and what we can do to fix it. Issue: openwisp/openwisp-users#256

@nemesisdesign Total of 38 `assertNumQueries` are failing, due to the addition of these permission classes `DjangoModelPermissions` and `IsOrganizationManager`. An also due to the modification of the `get_queryset` in two tests number of queries decreased.

### _Here is a Summary of it_:-

The test in which it increases by 2 in those cases It is due to the addition of `DjangoModelPermissions` permission class from `openwisp-users` module (becuase we have also added a permission check for the GET requests as well but the tests were written without those checks with the default rest-framework permission class) and those extra two queries are of this sort:-
```
2. SELECT "django_content_type"."app_label", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "openwisp_users_user_user_permissions" ON ("auth_permission"."id" = "openwisp_users_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "openwisp_users_user_user_permissions"."user_id" = '7798476dfa1e4dbcb65674b23c40c096'
3. SELECT "django_content_type"."app_label", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auth_group_permissions" ON ("auth_permission"."id" = "auth_group_permissions"."permission_id") INNER JOIN "auth_group" ON ("auth_group_permissions"."group_id" = "auth_group"."id") INNER JOIN "openwisp_users_user_groups" ON ("auth_group"."id" = "openwisp_users_user_groups"."group_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "openwisp_users_user_groups"."user_id" = '7798476dfa1e4dbcb65674b23c40c096'
```

The test in which it increases by 1 in those cases It is due to the addition of `IsOrganizationManager` permission class from `openwisp-users` module and those extra two queries are of this sort:-
```
5. SELECT "openwisp_users_organization"."name", "openwisp_users_organization"."is_active", "openwisp_users_organization"."created", "openwisp_users_organization"."modified", "openwisp_users_organization"."slug", "openwisp_users_organization"."id", "openwisp_users_organization"."description", "openwisp_users_organization"."email", "openwisp_users_organization"."url" FROM "openwisp_users_organization" WHERE "openwisp_users_organization"."id" = 'c11e66b739cf477c9786bcc099b954ae' LIMIT 21
```

and in cases in which there is increase of 3 are due to the combined queries from both of the classes.
