### ISSUE TITLE
Tests broken since celery>=4.4.3

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-firmware-upgrader#78]
[Tests are broken](https://travis-ci.org/github/openwisp/openwisp-firmware-upgrader/jobs/693522196)

After some debugging the reason seems to be the release of celery 4.4.3 two days ago. By downgrading to celery 4.4.2, tests pass again.

Celery changelog: https://github.com/celery/celery/blob/master/Changelog.rst

**Comment by nemesisdesign** [comment]
Thanks @PabloCastellano!

**Comment by PabloCastellano** [comment]
This has been fixed in celery 4.4.4, but unfortunately 4.4.4 is broken due to a missing dependency. We have to wait until 4.4.5 is released which will be probably soon.

**Comment by PabloCastellano** [comment]
Related: https://github.com/celery/celery/pull/6109 and https://github.com/celery/celery/pull/6137

**Comment by mchataigner** [comment]
Replying here as well:


So after some investigation in OpenWisp, it turns out that you have a couple of settings for your tests (in settings.py):
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True

This forces all tasks to be eager.

However,
This commit has been merged 26f24fa
changing the behaviour of _ensure_not_eager

previously it was raising a RuntimeError, now it's a simple warning.
In your tests, you expect a RuntimeError.

So I guess, you may update your tests.

**Comment by nemesisdesign** [comment]
Thanks a lot for the explanation @mchataigner, I'm updating the tests (#86).

Makes sense, I remember being confused on the fact that I was getting `RunTimeError` instead of the `Retry` exception. 

Although we would have expected this kind of change to be released in a point release (eg; celery 4.5.0) rather than a minor release. I guess that was unintentional? Thanks again for your help BTW.
